name: dimred
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=1_gnu
  - _tflow_select=2.3.0=eigen
  - absl-py=0.12.0=py38h06a4308_0
  - aiohttp=3.7.4=py38h27cfd23_1
  - anyio=2.2.0=py38h06a4308_0
  - appdirs=1.4.4=pyh9f0ad1d_0
  - argon2-cffi=20.1.0=py38h27cfd23_1
  - astunparse=1.6.3=py_0
  - async-timeout=3.0.1=py38h06a4308_0
  - async_generator=1.10=pyhd3eb1b0_0
  - attrs=20.3.0=pyhd3eb1b0_0
  - autopep8=1.5.5=pyhd3eb1b0_0
  - babel=2.9.0=pyhd3eb1b0_0
  - backcall=0.2.0=pyhd3eb1b0_0
  - blas=1.0=mkl
  - bleach=3.3.0=pyhd3eb1b0_0
  - blinker=1.4=py38h06a4308_0
  - blosc=1.20.1=hd408876_0
  - bokeh=2.2.3=py38_0
  - brotli=1.0.9=he6710b0_2
  - brotlipy=0.7.0=py38h27cfd23_1003
  - bzip2=1.0.8=h7b6447c_0
  - c-ares=1.17.1=h27cfd23_0
  - ca-certificates=2020.12.5=ha878542_0
  - cachetools=4.2.1=pyhd3eb1b0_0
  - certifi=2020.12.5=py38h578d9bd_1
  - cffi=1.14.5=py38h261ae71_0
  - cftime=1.4.1=py38h5c078b8_0
  - chardet=3.0.4=py38h06a4308_1003
  - charls=2.1.0=he6710b0_2
  - click=7.1.2=pyhd3eb1b0_0
  - cloudpickle=1.6.0=py_0
  - colorcet=2.0.6=pyhd3eb1b0_0
  - coverage=5.5=py38h27cfd23_2
  - cryptography=3.4.6=py38hd23ed53_0
  - curl=7.71.1=hbc83047_1
  - cycler=0.10.0=py38_0
  - cython=0.29.22=py38h2531618_0
  - cytoolz=0.11.0=py38h7b6447c_0
  - dask=2021.3.0=pyhd3eb1b0_0
  - dask-core=2021.3.0=pyhd3eb1b0_0
  - datashader=0.11.1=py_0
  - datashape=0.5.4=py38h06a4308_1
  - dbus=1.13.18=hb2f20db_0
  - decorator=4.4.2=pyhd3eb1b0_0
  - defusedxml=0.7.1=pyhd3eb1b0_0
  - distributed=2021.3.0=py38h06a4308_0
  - double-conversion=3.1.5=he6710b0_1
  - eigen=3.3.7=hfd86e86_0
  - entrypoints=0.3=py38_0
  - expat=2.2.10=he6710b0_2
  - ffmpeg=4.3.1=h3215721_1
  - fontconfig=2.13.1=hba837de_1004
  - freetype=2.10.4=h5ab3b9f_0
  - fsspec=0.8.7=pyhd3eb1b0_0
  - gast=0.3.3=py_0
  - giflib=5.1.4=h14c3975_1
  - gl2ps=1.4.2=h0708190_0
  - glew=2.1.0=he1b5a44_0
  - glib=2.67.4=h36276a3_1
  - gmp=6.2.1=h2531618_2
  - gnutls=3.6.13=h85f3911_1
  - google-auth=1.28.0=pyhd3eb1b0_0
  - google-auth-oauthlib=0.4.3=pyhd3eb1b0_0
  - google-pasta=0.2.0=py_0
  - grpcio=1.36.1=py38h2157cd5_1
  - gst-plugins-base=1.14.0=h8213a91_2
  - gstreamer=1.14.0=h28cd5cc_2
  - h5py=2.10.0=py38hd6299e0_1
  - hdbscan=0.8.27=py38h5c078b8_0
  - hdf4=4.2.13=h3ca952b_2
  - hdf5=1.10.6=nompi_h3c11f04_101
  - heapdict=1.0.1=py_0
  - holoviews=1.14.1=pyhd3eb1b0_0
  - icu=58.2=he6710b0_3
  - idna=2.10=pyhd3eb1b0_0
  - imagecodecs=2020.5.30=py38hfa7d478_2
  - imageio=2.9.0=py_0
  - importlib-metadata=3.7.3=py38h06a4308_1
  - importlib_metadata=3.7.3=hd3eb1b0_1
  - intel-openmp=2020.2=254
  - ipykernel=5.3.4=py38h5ca1d4c_0
  - ipython=7.21.0=py38hb070fc8_0
  - ipython_genutils=0.2.0=pyhd3eb1b0_1
  - jedi=0.17.0=py38_0
  - jinja2=2.11.3=pyhd3eb1b0_0
  - joblib=1.0.1=pyhd3eb1b0_0
  - jpeg=9d=h36c2ea0_0
  - json5=0.9.5=py_0
  - jsoncpp=1.8.4=hfd86e86_0
  - jsonschema=3.2.0=py_2
  - jupyter_client=6.1.7=py_0
  - jupyter_core=4.7.1=py38h06a4308_0
  - jupyter_server=1.4.1=py38h06a4308_0
  - jupyterlab=3.0.7=pyhd8ed1ab_0
  - jupyterlab_pygments=0.1.2=py_0
  - jupyterlab_server=2.3.0=pyhd3eb1b0_0
  - jxrlib=1.1=h7b6447c_2
  - keras-preprocessing=1.1.2=pyhd3eb1b0_0
  - kiwisolver=1.3.1=py38h2531618_0
  - krb5=1.18.2=h173b8e3_0
  - lame=3.100=h7b6447c_0
  - lcms2=2.11=h396b838_0
  - ld_impl_linux-64=2.33.1=h53a641e_7
  - libaec=1.0.4=he6710b0_1
  - libcurl=7.71.1=h20c2e04_1
  - libedit=3.1.20210216=h27cfd23_1
  - libffi=3.3=he6710b0_2
  - libgcc-ng=9.3.0=h2828fa1_18
  - libgfortran-ng=7.3.0=hdf63c60_0
  - libglu=9.0.0=hf484d3e_1
  - libgomp=9.3.0=h2828fa1_18
  - libiconv=1.16=h516909a_0
  - libllvm10=10.0.1=hbcb73fb_5
  - libnetcdf=4.7.4=nompi_h56d31a8_107
  - libogg=1.3.2=h7b6447c_0
  - libpng=1.6.37=hbc83047_0
  - libprotobuf=3.14.0=h8c45485_0
  - libsodium=1.0.18=h7b6447c_0
  - libssh2=1.9.0=h1ba5d50_1
  - libstdcxx-ng=9.1.0=hdf63c60_0
  - libtheora=1.1.1=h5ab3b9f_1
  - libtiff=4.1.0=h2733197_1
  - libuuid=2.32.1=h7f98852_1000
  - libvorbis=1.3.7=h7b6447c_0
  - libwebp=1.0.1=h8e7db2f_0
  - libxcb=1.14=h7b6447c_0
  - libxml2=2.9.10=hb55368b_3
  - libzopfli=1.0.3=he6710b0_0
  - llvmlite=0.34.0=py38h269e1b5_4
  - locket=0.2.1=py38h06a4308_1
  - loguru=0.5.3=py38h32f6830_2
  - lz4-c=1.9.2=heb0550a_3
  - markdown=3.3.4=py38h06a4308_0
  - markupsafe=1.1.1=py38h7b6447c_0
  - matplotlib=3.3.4=py38h06a4308_0
  - matplotlib-base=3.3.4=py38h62a2d02_0
  - meshio=4.3.8=pyhd8ed1ab_0
  - mistune=0.8.4=py38h7b6447c_1000
  - mkl=2020.2=256
  - mkl-service=2.3.0=py38he904b0f_0
  - mkl_fft=1.3.0=py38h54f3939_0
  - mkl_random=1.1.1=py38h0573a6f_0
  - msgpack-python=1.0.2=py38hff7bd54_1
  - multidict=5.1.0=py38h27cfd23_2
  - multipledispatch=0.6.0=py38_0
  - nbclassic=0.2.6=pyhd3eb1b0_0
  - nbclient=0.5.3=pyhd3eb1b0_0
  - nbconvert=6.0.7=py38_0
  - nbformat=5.1.2=pyhd3eb1b0_1
  - ncurses=6.2=he6710b0_1
  - nest-asyncio=1.5.1=pyhd3eb1b0_0
  - netcdf4=1.5.6=nompi_py38h1cdf482_100
  - nettle=3.6=he412f7d_0
  - networkx=2.5=py_0
  - notebook=6.3.0=py38h06a4308_0
  - numba=0.51.2=py38h0573a6f_1
  - numpy=1.19.2=py38h54aff64_0
  - numpy-base=1.19.2=py38hfa32c7d_0
  - oauthlib=3.1.0=py_0
  - olefile=0.46=py_0
  - openh264=2.1.1=h8b12597_0
  - openjpeg=2.3.0=h05c96fa_1
  - openssl=1.1.1j=h7f98852_0
  - opt_einsum=3.1.0=py_0
  - packaging=20.9=pyhd3eb1b0_0
  - pandas=1.2.1=py38ha9443f7_0
  - pandoc=2.12=h06a4308_0
  - pandocfilters=1.4.3=py38h06a4308_1
  - panel=0.10.3=pyhd3eb1b0_1
  - param=1.10.1=pyhd3eb1b0_0
  - parso=0.8.1=pyhd3eb1b0_0
  - partd=1.1.0=py_0
  - pcre=8.44=he6710b0_0
  - pexpect=4.8.0=pyhd3eb1b0_3
  - pickleshare=0.7.5=pyhd3eb1b0_1003
  - pillow=8.1.2=py38he98fc37_0
  - pip=21.0.1=py38h06a4308_0
  - proj=7.1.1=h966b41f_3
  - prometheus_client=0.9.0=pyhd3eb1b0_0
  - prompt-toolkit=3.0.17=pyh06a4308_0
  - protobuf=3.14.0=py38h2531618_1
  - psutil=5.8.0=py38h27cfd23_1
  - ptyprocess=0.7.0=pyhd3eb1b0_2
  - pugixml=1.10=he1b5a44_1
  - pyasn1=0.4.8=py_0
  - pyasn1-modules=0.2.8=py_0
  - pycodestyle=2.7.0=pyhd3eb1b0_0
  - pycparser=2.20=py_2
  - pyct=0.4.8=py38_0
  - pygments=2.8.1=pyhd3eb1b0_0
  - pyjwt=1.7.1=py38_0
  - pynndescent=0.5.2=pyhd3eb1b0_0
  - pyopenssl=20.0.1=pyhd3eb1b0_1
  - pyparsing=2.4.7=pyhd3eb1b0_0
  - pyqt=5.9.2=py38h05f1152_4
  - pyrsistent=0.17.3=py38h7b6447c_0
  - pysocks=1.7.1=py38h06a4308_0
  - python=3.8.8=hdb3f193_4
  - python-dateutil=2.8.1=pyhd3eb1b0_0
  - python_abi=3.8=1_cp38
  - pytz=2021.1=pyhd3eb1b0_0
  - pyvista=0.29.0=pyhd8ed1ab_0
  - pyviz_comms=2.0.1=pyhd3eb1b0_0
  - pywavelets=1.1.1=py38h7b6447c_2
  - pyyaml=5.4.1=py38h27cfd23_1
  - pyzmq=20.0.0=py38h2531618_1
  - qt=5.9.7=h5867ecd_1
  - readline=8.1=h27cfd23_0
  - requests=2.25.1=pyhd3eb1b0_0
  - requests-oauthlib=1.3.0=py_0
  - rsa=4.7.2=pyhd3eb1b0_1
  - scikit-image=0.17.2=py38hdf5156a_0
  - scikit-learn=0.23.2=py38h0573a6f_0
  - scipy=1.6.0=py38h91f5cce_0
  - scooby=0.5.6=pyh9f0ad1d_0
  - seaborn=0.11.1=pyhd3eb1b0_0
  - send2trash=1.5.0=pyhd3eb1b0_1
  - setuptools=52.0.0=py38h06a4308_0
  - sip=4.19.13=py38he6710b0_0
  - six=1.15.0=py38h06a4308_0
  - snappy=1.1.8=he6710b0_0
  - sniffio=1.2.0=py38h06a4308_1
  - sortedcontainers=2.3.0=pyhd3eb1b0_0
  - sqlite=3.35.2=hdfb4753_0
  - tbb=2020.3=hfd86e86_0
  - tbb-devel=2020.3=hfd86e86_0
  - tblib=1.7.0=py_0
  - tensorboard=2.4.0=pyhc547734_0
  - tensorboard-plugin-wit=1.6.0=py_0
  - tensorflow=2.3.0=eigen_py38h71ff20e_0
  - tensorflow-base=2.3.0=eigen_py38hb57a387_0
  - tensorflow-estimator=2.3.0=pyheb71bc4_0
  - termcolor=1.1.0=py38h06a4308_1
  - terminado=0.9.3=py38h06a4308_0
  - testpath=0.4.4=pyhd3eb1b0_0
  - threadpoolctl=2.1.0=pyh5ca1d4c_0
  - tifffile=2021.3.17=pyhd3eb1b0_1
  - tk=8.6.10=hbc83047_0
  - toml=0.10.2=pyhd3eb1b0_0
  - toolz=0.11.1=pyhd3eb1b0_0
  - tornado=6.1=py38h27cfd23_0
  - tqdm=4.59.0=pyhd3eb1b0_1
  - traitlets=5.0.5=pyhd3eb1b0_0
  - transforms3d=0.3.1=py_0
  - typing-extensions=3.7.4.3=hd3eb1b0_0
  - typing_extensions=3.7.4.3=pyh06a4308_0
  - umap-learn=0.5.1=py38h578d9bd_0
  - urllib3=1.26.4=pyhd3eb1b0_0
  - utfcpp=3.1.2=0
  - vtk=9.0.1=no_osmesa_py38h31de780_102
  - wcwidth=0.2.5=py_0
  - webencodings=0.5.1=py38_1
  - werkzeug=1.0.1=pyhd3eb1b0_0
  - wheel=0.36.2=pyhd3eb1b0_0
  - wrapt=1.12.1=py38h7b6447c_1
  - x264=1!152.20180806=h7b6447c_0
  - xarray=0.17.0=pyhd3eb1b0_0
  - xorg-kbproto=1.0.7=h7f98852_1002
  - xorg-libice=1.0.10=h7f98852_0
  - xorg-libsm=1.2.3=hd9c2040_1000
  - xorg-libx11=1.7.0=h7f98852_0
  - xorg-libxext=1.3.4=h7f98852_1
  - xorg-libxt=1.2.1=h7f98852_2
  - xorg-xextproto=7.3.0=h7f98852_1002
  - xorg-xproto=7.0.31=h27cfd23_1007
  - xz=5.2.5=h7b6447c_0
  - yaml=0.2.5=h7b6447c_0
  - yarl=1.6.3=py38h27cfd23_0
  - zeromq=4.3.4=h2531618_0
  - zict=2.0.0=pyhd3eb1b0_0
  - zipp=3.4.1=pyhd3eb1b0_0
  - zlib=1.2.11=h7b6447c_3
  - zstd=1.4.5=h9ceee32_0
prefix: /home/marc/miniconda3/envs/ml
